### ISSUE TITLE
decrypting my exported notes without Standard notes app

### ISSUE THREAD

**Issue by sidmint** [standardnotes/mobile#325]
Can I decrypt my exported notes on my computer without Standard notes app if I know the password? Please give some guide on how to do that.

Thank you for helping.

ver 3.5.8 on android

**Comment by bryvin** [comment]
I think you can use the Offline tool to decrypt your encrypted backup. Here is the page that describes how this works: https://standardnotes.org/offline

**Comment by sidmint** [comment]
Thanks, but for some reason the script isn't working and somewhat error like 'error came while decrypting, ensure your password is correct and try again' pop up comes [chromium 86.0.4240.198 32bit ]. I have more than double checked my password entry also.

**Comment by bryvin** [comment]
Oh my bad! I guess one of the team members will have to look into that. It could be due to the recent upgrades and encryption algorithms in the new versions of the app but I honestly have no clue. :(

**Comment by mobitar** [comment]
@baptiste-grob I think we need to update SNJS in the decrypt repo.

**Comment by baptiste-grob** [comment]
Hey @sidmint, I've just published an update to our decrypt tool, please let us know if the issue occurs again!

**Comment by sidmint** [comment]
I tested today and sorry to report that same issue is still occurring. I didn't build the latest script but used the download link hoping it's the latest too.

**Comment by JaspalSuri** [comment]
I'm sorry to hear that; thank you for letting us know. We've submitted an update to the Play Store for the Android app with a fix for how encrypted backups are exported. I'm afraid that the update is currently pending review, but we've made sure that it works with the decrypt script.

**Comment by sidmint** [comment]
verified fixed.

But I'm seeing another issue, the backups taken from android and web are different in two ways: 

1. they have different filenames, though this is not important.

2. the arrangement of notes inside them is different too. Will this affect its usage in anyway?
